cd $DITAC_HOME
echo "Building HTML docs:"
echo "Building CLI..."
( DOC_NAME=commandline-guide DOC_VER=3.2; $DITAC_HOME/bin/ditac  -f webhelp  -images img  -p use-note-icon yes  -p xsl-resources-directory css  -toc  -p chain-pages both  -p wh-jquery-ui ../../jquery-ui/js/jquery-ui-1.8.23.custom.min.js  -p wh-jquery-css ../../jquery-ui/css/custom-theme/jquery-ui-1.8.23.custom.css  -p wh-user-header ./whc_template/_wh/euca/header_$DOC_NAME.html  -p wh-user-resources ./whc_template/_wh/euca  -p wh-user-css ./whc_template/_wh/euca/eucadoc.css  -p wh-user-footer ./whc_template/_wh/euca/footer.html  -p wh-collapse-toc yes  -index  out/docs/$DOC_VER/$DOC_NAME/_.html $DOC_HOME/en_us/$DOC_NAME.ditamap )
echo "Building Console Guide..."
( DOC_NAME=console-guide DOC_VER=3.2; $DITAC_HOME/bin/ditac  -f webhelp  -images img  -p use-note-icon yes  -p xsl-resources-directory css  -toc  -p chain-pages both  -p wh-jquery-ui ../../jquery-ui/js/jquery-ui-1.8.23.custom.min.js  -p wh-jquery-css ../../jquery-ui/css/custom-theme/jquery-ui-1.8.23.custom.css  -p wh-user-header ./whc_template/_wh/euca/header_$DOC_NAME.html  -p wh-user-resources ./whc_template/_wh/euca  -p wh-user-css ./whc_template/_wh/euca/eucadoc.css  -p wh-user-footer ./whc_template/_wh/euca/footer.html  -p wh-collapse-toc yes  -index  out/docs/$DOC_VER/$DOC_NAME/_.html $DOC_HOME/en_us/$DOC_NAME.ditamap )
echo "Building FastStart Guide..."
( DOC_NAME=faststart-guide DOC_VER=3.2; $DITAC_HOME/bin/ditac  -f webhelp  -images img  -p use-note-icon yes  -p xsl-resources-directory css  -toc  -p chain-pages both  -p wh-jquery-ui ../../jquery-ui/js/jquery-ui-1.8.23.custom.min.js  -p wh-jquery-css ../../jquery-ui/css/custom-theme/jquery-ui-1.8.23.custom.css  -p wh-user-header ./whc_template/_wh/euca/header_$DOC_NAME.html  -p wh-user-resources ./whc_template/_wh/euca  -p wh-user-css ./whc_template/_wh/euca/eucadoc.css  -p wh-user-footer ./whc_template/_wh/euca/footer.html  -p wh-collapse-toc yes  -index  out/docs/$DOC_VER/$DOC_NAME/_.html $DOC_HOME/en_us/$DOC_NAME.ditamap )
echo "Building Install Guide..."
( DOC_NAME=install-guide DOC_VER=3.2; $DITAC_HOME/bin/ditac  -f webhelp  -images img  -p use-note-icon yes  -p xsl-resources-directory css  -toc  -p chain-pages both  -p wh-jquery-ui ../../jquery-ui/js/jquery-ui-1.8.23.custom.min.js  -p wh-jquery-css ../../jquery-ui/css/custom-theme/jquery-ui-1.8.23.custom.css  -p wh-user-header ./whc_template/_wh/euca/header_$DOC_NAME.html  -p wh-user-resources ./whc_template/_wh/euca  -p wh-user-css ./whc_template/_wh/euca/eucadoc.css  -p wh-user-footer ./whc_template/_wh/euca/footer.html  -p wh-collapse-toc yes  -index  out/docs/$DOC_VER/$DOC_NAME/_.html $DOC_HOME/en_us/$DOC_NAME.ditamap )
echo "Building User Guide..."
( DOC_NAME=user-guide DOC_VER=3.2; $DITAC_HOME/bin/ditac  -f webhelp  -images img  -p use-note-icon yes  -p xsl-resources-directory css  -toc  -p chain-pages both  -p wh-jquery-ui ../../jquery-ui/js/jquery-ui-1.8.23.custom.min.js  -p wh-jquery-css ../../jquery-ui/css/custom-theme/jquery-ui-1.8.23.custom.css  -p wh-user-header ./whc_template/_wh/euca/header_$DOC_NAME.html  -p wh-user-resources ./whc_template/_wh/euca  -p wh-user-css ./whc_template/_wh/euca/eucadoc.css  -p wh-user-footer ./whc_template/_wh/euca/footer.html  -p wh-collapse-toc yes  -index  out/docs/$DOC_VER/$DOC_NAME/_.html $DOC_HOME/en_us/$DOC_NAME.ditamap )
echo "Building Release Notes..."
( DOC_NAME=release-notes DOC_VER=3.2; $DITAC_HOME/bin/ditac  -f webhelp  -images img  -p use-note-icon yes  -p xsl-resources-directory css  -toc  -p chain-pages both  -p wh-jquery-ui ../../jquery-ui/js/jquery-ui-1.8.23.custom.min.js  -p wh-jquery-css ../../jquery-ui/css/custom-theme/jquery-ui-1.8.23.custom.css  -p wh-user-header ./whc_template/_wh/euca/header_$DOC_NAME.html  -p wh-user-resources ./whc_template/_wh/euca  -p wh-user-css ./whc_template/_wh/euca/eucadoc.css  -p wh-user-footer ./whc_template/_wh/euca/footer.html  -p wh-collapse-toc yes  -index  out/docs/$DOC_VER/$DOC_NAME/_.html $DOC_HOME/en_us/$DOC_NAME.ditamap )
