/*
 * Copyright (c) 2009-2010 Pixware SARL. All rights reserved.
 *
 * Author: Hussein Shafie
 *
 * This file is part of the XMLmind DITA Converter project.
 * For conditions of distribution and use, see the accompanying LEGAL.txt file.
 */
package com.xmlmind.ditac.convert;

import java.io.File;
import com.xmlmind.util.Console;

/**
 * Interface allowing the Converter to use the services of 
 * an XSL-FO processor such as Apache FOP, RenderX XEP, etc.
 */
public interface FOConverter {
    /**
     * Returns the name of this XSL-FO processor, something very short like
     * "<tt>FOP</tt>", "<tt>XEP</tt>", "<tt>XFC</tt>". Note that this name 
     * is passed as the value of the <tt>foProcessor</tt> ``system parameter'' 
     * to the XSLT stylesheets that generate XSL-FO.
     */
    String getProcessorName();
    
    /**
     * Returns the format generated by this XSL-FO processor.
     */
    Format getTargetFormat();

    /**
     * Converts specified input XSL-FO file to specified output file.
     * 
     * @param inFile input XSL-FO file
     * @param outFile output file
     * @param console Console on which progress, trace, debug, etc, message
     * can be displayed. May be <code>null</code>.
     * @exception Exception if, for any reason, this operation fails
     */
    void convertFO(File inFile, File outFile, Console console)
        throws Exception;
}
